### ISSUE TITLE
Does not throw on parse errors

### ISSUE THREAD

**Issue by giuseppeg** [esamattis/react-zorm#17]
Hey there! Loving this library so thank you for the hard work and for open sourcing it!

Today I was thinking that for consistency sake it'd be nice if `parseForm` used zod's `safeParse` instead of `parse` therefore returning the error(s) instead of throwing.

This would play better with `createCustomIssues` in that one could combine those with `parseForm`'s errors and handle errors in a consistent way.

Please let me know if I am missing something because the library is still new to me ✌️

**Comment by esamattis** [comment]
Thanks! 

You can also import safeParseForm() which uses the Zod's safeParse() 


https://github.com/esamattis/react-zorm#safeparseformform-schema-safeparsereturntype

**Comment by giuseppeg** [comment]
ouch I knew I should have read everything carefully! Thanks :)
