### ISSUE TITLE
Can I use with Radix UI Select?

### ISSUE THREAD

**Issue by juliusmarminge** [esamattis/react-zorm#29]
Trying to stitch together RadixUI's Select and my react-zorm form but can't get the values to sync.

This is my code:

```jsx
export const MyComp = () => {

  const zo = useZorm("update-formatting", UpdateFormSchema, {
    onValidSubmit(e) {
      e.preventDefault();
      console.log("FormData:", e.data);
    },
  });

  return (
    <div>
      {/* Form */}
      <div>
        <form ref={zo.ref}>
          {/* Language Selector */}
          <div>
            <label
              htmlFor={zo.fields.language("id")}
            >
              Language
            </label>
            <Select.Root
              defaultValue={language}
              name={zo.fields.language("name")}
              onValueChange={(value) => {
                console.log("Lang onChange", value);
              }}
            >
              <Select.Trigger>
                <Select.Value aria-label={language}>{language}</Select.Value>
                <Select.Icon />
              </Select.Trigger>

              <Select.Portal>
                <Select.Content>
                  <Select.Viewport>
                    {langs.map((item) => (
                      <Select.Item
                        key={item.key}
                        value={item.key}
                      >
                        <Select.ItemText>
                          <item.icon />
                          <p>{item.key}</p>
                        </Select.ItemText>
                        <Select.ItemIndicator>
                          <HiCheckCircle />
                        </Select.ItemIndicator>
                      </Select.Item>
                    ))}
                  </Select.Viewport>
                </Select.Content>
              </Select.Portal>
            </Select.Root>
          </div>
        </form>
     </div>
  );
};
```

Which renders the following DOM:

![image](https://user-images.githubusercontent.com/51714798/205437235-57f92235-8c66-429b-8693-41cb2ed64500.png)

But the onChange Radix gives doesn't change the selected item in the select:

https://user-images.githubusercontent.com/51714798/205437256-a3f3ef7c-aef7-4bd6-9e6c-d40cc8d0c90e.mp4

Any idea what I'm doing wrong?

**Comment by esamattis** [comment]
Really hard to say since you did't share the full code.

But I tried Radix UI Select on Codesandbox:

https://codesandbox.io/s/goofy-bush-lqv3me?file=/src/App.tsx

I just copied their [example](https://www.radix-ui.com/docs/primitives/components/select). The only change I had to make was to add `name="fruit"` to the `<Select.Root>` component in order the get the `name` attribute on the `<select>` so the native `<form>` can see it. Nothing Zorm specific was required 🤔

**Comment by juliusmarminge** [comment]
Ok, so the problem seems to be that the value i get from useValue isn't synced with the value used for validation:

![CleanShot 2022-12-04 at 14 06 32](https://user-images.githubusercontent.com/51714798/205492232-ebd796c2-c60f-4bb3-ae5a-ad25899abed3.png)

Here, you see the selected language is DE which passes validation, but the value printed above is blank - that value comes from useValue hook

```ts
  const language = useValue({
    zorm: zo,
    name: zo.fields.language(),
    initialValue: Language.EN,
  });
```

**Comment by juliusmarminge** [comment]
Repro here: https://codesandbox.io/s/sweet-turing-6rnfnr?file=/src/App.tsx

**Comment by esamattis** [comment]
That repro gives `Cannot read properties of undefined (reading 'refObject')`.

But I think I figured it out. The `useValue()` hook works by [listening](https://github.com/esamattis/react-zorm/blob/0b4355a37415b974cab9e1e276958aaaf847ab68/packages/react-zorm/src/use-value.ts#L50-L56) on the `input` event on the form element but the Radix Select does not bubble it for some reason like the native `<select>` select does. This could be a bug in Radix Select.

But you can workaround by listening on the `change` event instead:

```tsx
  const fruit = useValue({
    name: zo.fields.fruit(),
    event: "change",
    zorm: zo
  });
```

Demo https://codesandbox.io/s/xenodochial-shaw-wip6er?file=/src/App.tsx

Also you could have also just made the Radix Select a controlled component using `useState()` with its onChange handlers.

**Comment by juliusmarminge** [comment]
Oh sorry snook a Value component in there which didn't quite work - didn't know that followed the repro...

Updated: https://codesandbox.io/s/infallible-boyd-x5xhjv?file=/src/App.tsx

https://share.cleanshot.com/erV1X8 - with `event: change` it works. Thanks

**Comment by juliusmarminge** [comment]
Regarding useState - yes I know I could have done that but we wanted to keep the Form Web API
