### ISSUE TITLE
Not updating on state change

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [esamattis/react-zorm#32]
I have a simple form with a `url` field, so I need to transform the value and replace `'  '` with `-`, I setup the `<Value />` component but the input is not updating onChange.

``` typescriptreact
<fieldset className={`flex items-center rounded-lg border border-inputBorder px-3 py-2`}>
          <span className="text-realmLink">dimension.dev/</span>

          <Value
            zorm={zorm}
            initialValue={props.prevValues?.slug}
            name={zorm.fields.slug()}
            transform={(v) => v.split(" ").join("-")}
          >
            {(value) => (
              <input
                type="text"
                className="w-full bg-transparent focus:outline-none"
                defaultValue={value}
              />
            )}
          </Value>
        </fieldset>
```

<img width="659" alt="Screenshot 2023-01-24 at 09 04 01" src="https://user-images.githubusercontent.com/74371045/214315151-2263fcb6-2887-4319-afa1-21f80d6ed834.png">

expected behavior: value should be `a-b-c`

**Comment by esamattis** [comment]
Not quite sure what you are trying to do. You talk about some `onChange` handler, but where is that? Your example does not contain it.

But you cannot update input value using `defaultValue` it only sets the initial value for the uncontrolled input you have there. `<Value>` is only for displaying the input values, not managing input state. I think you just want a normal controlled input using `useState()`. See  https://beta.reactjs.org/reference/react-dom/components/input#controlling-an-input-with-a-state-variable

If this is not what you are looking for and think you have found a bug in React Zorm, could you provide repro using Codesandbox, so I would not have to guess? Thank you.

**Comment by AlvaroAquijeDiaz** [comment]
- what I meant was that the `<Value>` component was not actually `transforming` the values passed to it via the input field.

But yes, I ended up using `useState` and `useRef` and just updating the form values afterwards
