### ISSUE TITLE
When validation.success is true, the data property throws a typescript error that it doesn't exist

### ISSUE THREAD

**Issue by yamilelias** [esamattis/react-zorm#33]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**

When using `validation.data` to use it after success, the data throws a typescript error that the schema's properties don't exist (even when the data is correctly set). See the example below:

![image](https://user-images.githubusercontent.com/9338305/225422412-a0d72bad-056f-48d1-943c-66b94035ce9f.png)
![image](https://user-images.githubusercontent.com/9338305/225422451-77ab28cf-218f-45cc-80e4-aafc1151b6aa.png)

https://codesandbox.io/s/react-zorm-issue-8p7xhg

**What is the expected behavior?**

To access the data from the properties correctly, because it is what is [returned](https://github.com/esamattis/react-zorm#return-zorm) by zod's [safeParse()](https://github.com/colinhacks/zod/blob/cc8ad1981ba580d1250520fde8878073d4b7d40a/README.md#safeparse)

**Comment by esamattis** [comment]
This looks like a bug alright. Thanks for reporting. Will look into it.

**Comment by esamattis** [comment]
@yamilelias  Made a prerelease in #33 which you can try out

```
npm install --save-exact react-zorm@0.6.1-dev.9b9e116ac9
```

**Comment by yamilelias** [comment]
It is working! I made it work on my project too. Thanks!

**Comment by esamattis** [comment]
Out with v0.6.2!
