### ISSUE TITLE
Double submit button

### ISSUE THREAD

**Issue by d90375** [esamattis/react-zorm#50]
Hello. Could you help pls. How we can solve double submit button like ['save', 'submit']. Two button related one form.

**Comment by esamattis** [comment]
So you want to have two submit buttons and detect which one was pressed?

If you need to detect that on the server-side you can just add `name` and `value` attributes to the submit buttons which will be visible on the server-side form submission. But if you need that on the client or when POSTing JSON you'll need to detect it with click handlers.

One way to do it would be to track the pressed submit-button with `useRef` and then to inject the button info to the form with the `formdata` event.

Here's how to do it:
 
https://codesandbox.io/s/beautiful-panka-w4pbcr?file=/src/App.tsx

This way the submitter will be available on the client and on the server-side.


------------


Closing this issue as it is not actionable on React Zorm but feel free to continue the discussion.

**Comment by d90375** [comment]
@esamattis thanks but i mean double different scheme validation for same form. two button have different validation scheme. Data of fields is same. The main purpose is validation for two different buttons.

**Comment by esamattis** [comment]
Ah. That's an excotic use case 😅 

But sure, you can put the form schema to the component state like this

https://codesandbox.io/s/nostalgic-drake-znxo0b?file=/src/App.tsx

And have the form to validate based on that.

Some considerations if you do this:

- You'll probably need to submit the form manually
- You need to manually call the validate method when you swap the schema
- The form schemas must have the same fields or otherwise the chains will break

**Comment by d90375** [comment]
@esamattis Thanks a lot. That's I rly need. 
But maybe u could help with one exotic case. Can i provide value from server (response BE) in max or min value ? For ex. have object like {maxCount : 3} and i need put 3 to max(3). Something like dynamic scheme. I didn't find answer with google. Sorry i newb with zod :)

**Comment by esamattis** [comment]
If you need dynamic schema, you can just generate the schema dynamically. Just be sure to use `useMemo()` to avoid regenerating the `zo` object on every render. 


Ex. 

```tsx

function MyForm() {

    // Data from the server Remix style
    const data = useLoaderData<typeof loader>();

    const FormSchema = useMemo(() => z.object({
      count: z.number().max(data.maxCount),
    }), [data.maxCount]);


    const zo = useZorm("myform", FormSchema);


    return (
        <form ref={zo.ref} >
    	// ...
    );

}
```

**Comment by d90375** [comment]
@esamattis one more thing about example 2.
![image](https://user-images.githubusercontent.com/18696683/229698980-9057c839-efd5-420a-8341-ce6322ee9638.png)

could we join 2 examples and figure out button inside hook relying on state [schema, setSchema]
https://codesandbox.io/s/practical-fog-li7cxv?file=/src/App.tsx

**Comment by esamattis** [comment]
Not quite sure I'm understanding what you are asking 🤔  Like can you change the schema and submit the form from the same button click?

That's bit tricky because you need to do one render pass to update the schema and only after that submit it. But it's possible by using a flag and and useEffect. Set a flag from (to useState) from the button click indicating that you want to submit the form. Change the schema. Monitor schema and the flag changes in useEffect and inside that that effect submit the form manually if the flag was true. And reset the flag to avoid unwanted submissions.

**Comment by d90375** [comment]
@esamattis i've created mini example what i need. Could you help me solve this problem ? in advance thanks a lot !!!
https://codesandbox.io/s/busy-tamas-d1v1oo
double submit buttons and double schemes, and issue with empty array for first scheme

**Comment by d90375** [comment]
@esamattis do you have any idea?  I apologize for the frequent treatment but I need solve this :(

**Comment by esamattis** [comment]
I'm sorry, I'm afraid I don't understand what you are trying to do. Also this is not a React help forum. You might have better luck asking on a more general forum as this is not an issue in React Zorm itself.

**Comment by d90375** [comment]
> I'm sorry, I'm afraid I don't understand what you are trying to do. Also this is not a React help forum. You might have better luck asking on a more general forum as this is not an issue in React Zorm itself. 

OK thanks. How I can validate array of strings only for max length? If I use selector(without input tag) and set value through form Data (onFormData injection).
Form do not work if I don't inject value, but value is empty array.

**Comment by d90375** [comment]
I've found solution. This is .default([])
sorry for distracting you

**Comment by d90375** [comment]
@esamattis And one more question about zorm ofc.
I need change behaviour for submitting. When i have one form and one input onBlur validation looks strange (because i need to click outside input). I need change validation onChange after first submit.I know that i can put zo.validation() inside onChange callback of input but how i can figure out that submit form already(firstly) pressed.
Procedure of actions: 
First click onSubmit -> disable onSubmit btn, input some letters inside input -> unblock onSubmit btn
