### ISSUE TITLE
Add way to clear form

### ISSUE THREAD

**Issue by elmarvr** [esamattis/react-zorm#51]

**Comment by elmarvr** [comment]
```
{
    onValidSubmit(event) {
      event.preventDefault();

      submit(event.target);

      event.target.reset();
    },
  }
```

**Comment by esamattis** [comment]
Yup. [HTMLFormElement#reset()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset)

Remix video about the topic (applicable to other frameworks as well)
https://www.youtube.com/watch?v=bMLej7bg5Zo
