### ISSUE TITLE
Bug: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by alexluong** [esamattis/react-zorm#7]
I'm trying `react-zorm` with Remix and run into this issue.

https://github.com/esamattis/react-zorm/blob/6deb4270501766b12f968bf147114c858bd29a84/packages/react-zorm/src/use-zorm.tsx#L45

I think in here it should be

```ts
    if (typeof document !== "undefined") {
        // ...
    }
```

**Comment by esamattis** [comment]
Thanks for the report! v0.2.2 will be out soon with this.
